### ISSUE TITLE
Hi bro, do you know about generate cross section on map of react leaflet?

### ISSUE THREAD

**Issue by hoangdangcodecomplete** [tomik23/react-leaflet-examples#5]

**Comment by tomik23** [comment]
You can elaborate on this part "cross section on map"? Bro ;)

**Comment by hoangdangcodecomplete** [comment]
@tomik23 the cross-section I mean like that [](https://uh.edu/~jbutler/physical/blockdiagram.jpg). I've been trying to find out but haven't seen anyone use it on Map. So if you know about this section, please help me. Thank you!

**Comment by tomik23** [comment]
Unfortunately, I have not encountered such kind of maps. So I can't help.
Put this question in the "Discussions" tab, maybe someone met with it and will be able to help.

Good luck
